# Generated by Django 4.1.7 on 2023-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_rooms_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Contact_No', models.IntegerField()),
                ('Check_In', models.DateField()),
            ],
        ),
    ]
