# Generated by Django 4.1.7 on 2023-05-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
