# Generated by Django 4.1.7 on 2023-05-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0005_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='comments',
        ),
    ]
